const INVALID_REFRESH_TOKEN=process.env.REACT_APP_INVALID_REFRESH_TOKEN
const REFRESH_TOKEN_UNAUTHORIZED=process.env.REACT_APP_REFRESH_TOKEN_UNAUTHORIZED


const INVALID_ACCESS_TOKEN=process.env.REACT_APP_INVALID_ACCESS_TOKEN
const ACCESS_TOKEN_UNAUTHORIZED=process.env.REACT_APP_ACCESS_TOKEN_UNAUTHORIZED

const INVALID_VALIDATION_TOKEN=process.env.REACT_APP_INVALID_VALIDATION_TOKEN
const VALIDATION_TOKEN_UNAUTHORIZED=process.env.REACT_APP_VALIDATION_TOKEN_UNAUTHORIZED
const VALIDATION_TOKEN_MISMATCH=process.env.REACT_APP_VALIDATION_TOKEN_MISMATCH

const ACTE_NOT_FOUND=process.env.REACT_APP_ACTE_NOT_FOUND
const REGISTRE_NOT_FOUND=process.env.REACT_APP_REGISTRE_NOT_FOUND
export {
    INVALID_REFRESH_TOKEN,
    REFRESH_TOKEN_UNAUTHORIZED,

    INVALID_ACCESS_TOKEN,
    ACCESS_TOKEN_UNAUTHORIZED,

    INVALID_VALIDATION_TOKEN,
    VALIDATION_TOKEN_UNAUTHORIZED,
    VALIDATION_TOKEN_MISMATCH,
    ACTE_NOT_FOUND,
    REGISTRE_NOT_FOUND
}