export const STATUS ={
    NAISSANCE:"NAISSANCE",
    DECES:"DECES",
    MARIAGE:"MARIAGE",
}
export const STATUS_ATTRIBUTS={
    DATE:"DATE",
    LIEU:"LIEU",
    NUMERO_ACTE:"NUMERO_ACTE"
}
export const ARRAY_STATUS_ATTRIBUTS=[STATUS_ATTRIBUTS.DATE,STATUS_ATTRIBUTS.LIEU,STATUS_ATTRIBUTS.NUMERO_ACTE]
export const ARRAY_STATUS=[STATUS.NAISSANCE,STATUS.DECES,STATUS.MARIAGE]